<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            [
                'name' => 'ABC Manufacturing Ltd',
                'email' => 'info@abcmanufacturing.co.tz',
                'phone' => '+255 22 211 1234',
                'industry' => 'Manufacturing',
                'address' => 'Nyerere Road, Industrial Area',
                'city' => 'Dar es Salaam',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 1234',
                'website' => 'https://www.abcmanufacturing.co.tz',
                'contact_person' => 'Michael Mwangi',
                'contact_title' => 'HR Director',
                'contact_email' => 'm.mwangi@abcmanufacturing.co.tz',
                'contact_phone' => '+255 754 123 456',
                'status' => 'active',
                'subscription_plan' => 'enterprise',
                'employee_count' => 250,
                'notes' => 'Long-term client since 2020. Manufacturing company with multiple locations.',
            ],
            [
                'name' => 'XYZ Construction Co',
                'email' => 'contact@xyzconstruction.com',
                'phone' => '+255 22 215 5678',
                'industry' => 'Construction',
                'address' => 'Kaweya Road, Mikocheni',
                'city' => 'Dar es Salaam',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 5678',
                'website' => 'https://www.xyzconstruction.com',
                'contact_person' => 'Sarah Kimani',
                'contact_title' => 'Operations Manager',
                'contact_email' => 'sarah.k@xyzconstruction.com',
                'contact_phone' => '+255 756 789 012',
                'status' => 'active',
                'subscription_plan' => 'premium',
                'employee_count' => 150,
                'notes' => 'Construction company specializing in commercial buildings.',
            ],
            [
                'name' => 'Tanzania Mining Corp',
                'email' => 'admin@tzmining.co.tz',
                'phone' => '+255 25 250 1111',
                'industry' => 'Mining',
                'address' => 'Sokoine Drive, City Centre',
                'city' => 'Mbeya',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 9012',
                'website' => 'https://www.tzmining.co.tz',
                'contact_person' => 'James Mwalimu',
                'contact_title' => 'General Manager',
                'contact_email' => 'j.mwalimu@tzmining.co.tz',
                'contact_phone' => '+255 765 345 678',
                'status' => 'active',
                'subscription_plan' => 'enterprise',
                'employee_count' => 500,
                'notes' => 'Large mining operation with multiple sites across Tanzania.',
            ],
            [
                'name' => 'East Africa Logistics',
                'email' => 'info@ealogistics.com',
                'phone' => '+255 22 213 9999',
                'industry' => 'Logistics',
                'address' => 'Julius Nyerere International Airport Area',
                'city' => 'Dar es Salaam',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 3456',
                'website' => 'https://www.ealogistics.com',
                'contact_person' => 'Grace Kileo',
                'contact_title' => 'Managing Director',
                'contact_email' => 'grace@ealogistics.com',
                'contact_phone' => '+255 757 890 123',
                'status' => 'active',
                'subscription_plan' => 'premium',
                'employee_count' => 80,
                'notes' => 'Logistics and transportation company serving East Africa.',
            ],
            [
                'name' => 'Kilimanjaro Tours Ltd',
                'email' => 'bookings@kilimanjarotours.co.tz',
                'phone' => '+255 27 275 1234',
                'industry' => 'Tourism',
                'address' => 'Moshi-Arusha Road',
                'city' => 'Moshi',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 7890',
                'website' => 'https://www.kilimanjarotours.co.tz',
                'contact_person' => 'Peter Moshi',
                'contact_title' => 'Tour Operations Manager',
                'contact_email' => 'peter@kilimanjarotours.co.tz',
                'contact_phone' => '+255 754 567 890',
                'status' => 'inactive',
                'subscription_plan' => 'basic',
                'employee_count' => 25,
                'notes' => 'Tourism company specializing in Kilimanjaro climbing and safari tours.',
            ],
            [
                'name' => 'Dar es Salaam Port Authority',
                'email' => 'info@portauthority.go.tz',
                'phone' => '+255 22 211 0000',
                'industry' => 'Government',
                'address' => 'Port Area, Kigamboni',
                'city' => 'Dar es Salaam',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 1111',
                'website' => 'https://www.portauthority.go.tz',
                'contact_person' => 'John Mwanga',
                'contact_title' => 'Administrative Director',
                'contact_email' => 'j.mwanga@portauthority.go.tz',
                'contact_phone' => '+255 758 234 567',
                'status' => 'active',
                'subscription_plan' => 'enterprise',
                'employee_count' => 1000,
                'notes' => 'Government agency managing Dar es Salaam port operations.',
            ],
            [
                'name' => 'Mwanza Textile Mills',
                'email' => 'hr@mwanzatextile.co.tz',
                'phone' => '+255 28 250 7777',
                'industry' => 'Textile',
                'address' => 'Industrial Area, Nyakato',
                'city' => 'Mwanza',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 2345',
                'website' => 'https://www.mwanzatextile.co.tz',
                'contact_person' => 'Anna Mwangi',
                'contact_title' => 'HR Manager',
                'contact_email' => 'anna.m@mwanzatextile.co.tz',
                'contact_phone' => '+255 759 345 678',
                'status' => 'suspended',
                'subscription_plan' => 'basic',
                'employee_count' => 45,
                'notes' => 'Textile manufacturing company currently under suspension.',
            ],
            [
                'name' => 'Zanzibar Spice Company',
                'email' => 'info@zanzibarspice.com',
                'phone' => '+255 24 223 3333',
                'industry' => 'Agriculture',
                'address' => 'Stone Town, Zanzibar',
                'city' => 'Zanzibar',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 6789',
                'website' => 'https://www.zanzibarspice.com',
                'contact_person' => 'Hassan Ali',
                'contact_title' => 'Managing Director',
                'contact_email' => 'hassan@zanzibarspice.com',
                'contact_phone' => '+255 771 234 567',
                'status' => 'active',
                'subscription_plan' => 'premium',
                'employee_count' => 60,
                'notes' => 'Spice processing and export company based in Zanzibar.',
            ],
            [
                'name' => 'Arusha Tech Solutions',
                'email' => 'contact@arushatech.co.tz',
                'phone' => '+255 27 254 8888',
                'industry' => 'Technology',
                'address' => 'Njiro Complex, Arusha',
                'city' => 'Arusha',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 4567',
                'website' => 'https://www.arushatech.co.tz',
                'contact_person' => 'David Kimario',
                'contact_title' => 'CEO',
                'contact_email' => 'david@arushatech.co.tz',
                'contact_phone' => '+255 762 345 678',
                'status' => 'active',
                'subscription_plan' => 'basic',
                'employee_count' => 30,
                'notes' => 'IT solutions company serving businesses in Northern Tanzania.',
            ],
            [
                'name' => 'Tanga Cement Company',
                'email' => 'hr@tangacement.co.tz',
                'phone' => '+255 31 262 1111',
                'industry' => 'Construction Materials',
                'address' => 'Industrial Area, Tanga',
                'city' => 'Tanga',
                'country' => 'Tanzania',
                'postal_code' => 'P.O. Box 8901',
                'website' => 'https://www.tangacement.co.tz',
                'contact_person' => 'Robert Mlay',
                'contact_title' => 'HR Director',
                'contact_email' => 'r.mlay@tangacement.co.tz',
                'contact_phone' => '+255 763 456 789',
                'status' => 'active',
                'subscription_plan' => 'enterprise',
                'employee_count' => 300,
                'notes' => 'Cement manufacturing company with nationwide distribution.',
            ],
        ];

        foreach ($clients as $clientData) {
            Client::firstOrCreate(
                ['email' => $clientData['email']],
                $clientData
            );
        }
    }
}
