<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\Client;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = Client::all();
        
        foreach ($clients as $client) {
            // Create sample employees for each client
            $employees = [
                [
                    'first_name' => 'John',
                    'last_name' => 'Mwangi',
                    'email' => 'john.mwangi+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 001',
                    'gender' => 'male',
                    'date_of_birth' => '1985-06-15',
                    'national_id' => '198506150001',
                    'position' => 'HR Manager',
                    'department' => 'Human Resources',
                    'employment_type' => 'full_time',
                    'status' => 'active',
                    'salary' => 2500000.00,
                    'bank_account' => '0123456789001',
                    'bank_name' => 'CRDB Bank',
                    'address' => 'Kijitonyama, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 1234',
                    'emergency_contact_name' => 'Mary Mwangi',
                    'emergency_contact_phone' => '+255 754 123 002',
                    'hire_date' => '2020-01-15',
                ],
                [
                    'first_name' => 'Grace',
                    'last_name' => 'Kimario',
                    'email' => 'grace.kimario+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 003',
                    'gender' => 'female',
                    'date_of_birth' => '1990-03-22',
                    'national_id' => '199003220002',
                    'position' => 'Finance Officer',
                    'department' => 'Finance & Accounting',
                    'employment_type' => 'full_time',
                    'status' => 'active',
                    'salary' => 1800000.00,
                    'bank_account' => '0123456789002',
                    'bank_name' => 'NBC Bank',
                    'address' => 'Mikocheni, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 5678',
                    'emergency_contact_name' => 'David Kimario',
                    'emergency_contact_phone' => '+255 754 123 004',
                    'hire_date' => '2021-03-10',
                ],
                [
                    'first_name' => 'Peter',
                    'last_name' => 'Mosha',
                    'email' => 'peter.mosha+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 005',
                    'gender' => 'male',
                    'date_of_birth' => '1988-11-08',
                    'national_id' => '198811080003',
                    'position' => 'Software Developer',
                    'department' => 'Information Technology',
                    'employment_type' => 'full_time',
                    'status' => 'active',
                    'salary' => 2200000.00,
                    'bank_account' => '0123456789003',
                    'bank_name' => 'KCB Bank',
                    'address' => 'Masaki, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 9012',
                    'emergency_contact_name' => 'Anna Mosha',
                    'emergency_contact_phone' => '+255 754 123 006',
                    'hire_date' => '2022-06-01',
                ],
                [
                    'first_name' => 'Sarah',
                    'last_name' => 'Mwalimu',
                    'email' => 'sarah.mwalimu+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 007',
                    'gender' => 'female',
                    'date_of_birth' => '1992-07-14',
                    'national_id' => '199207140004',
                    'position' => 'Marketing Officer',
                    'department' => 'Sales & Marketing',
                    'employment_type' => 'full_time',
                    'status' => 'active',
                    'salary' => 1500000.00,
                    'bank_account' => '0123456789004',
                    'bank_name' => 'ACB Bank',
                    'address' => 'Sinza, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 3456',
                    'emergency_contact_name' => 'James Mwalimu',
                    'emergency_contact_phone' => '+255 754 123 008',
                    'hire_date' => '2023-01-20',
                ],
                [
                    'first_name' => 'Michael',
                    'last_name' => 'Kileo',
                    'email' => 'michael.kileo+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 009',
                    'gender' => 'male',
                    'date_of_birth' => '1987-09-03',
                    'national_id' => '198709030005',
                    'position' => 'Operations Manager',
                    'department' => 'Operations',
                    'employment_type' => 'full_time',
                    'status' => 'active',
                    'salary' => 2800000.00,
                    'bank_account' => '0123456789005',
                    'bank_name' => 'DTB Bank',
                    'address' => 'Ubungo, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 7890',
                    'emergency_contact_name' => 'Grace Kileo',
                    'emergency_contact_phone' => '+255 754 123 010',
                    'hire_date' => '2019-11-15',
                ],
                [
                    'first_name' => 'Fatuma',
                    'last_name' => 'Hassan',
                    'email' => 'fatuma.hassan+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 011',
                    'gender' => 'female',
                    'date_of_birth' => '1991-12-08',
                    'national_id' => '199112080006',
                    'position' => 'Administrative Assistant',
                    'department' => 'Administration',
                    'employment_type' => 'full_time',
                    'status' => 'active',
                    'salary' => 600000.00,
                    'bank_account' => '0123456789006',
                    'bank_name' => 'Exim Bank',
                    'address' => 'Kinondoni, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 2345',
                    'emergency_contact_name' => 'Omar Hassan',
                    'emergency_contact_phone' => '+255 754 123 012',
                    'hire_date' => '2022-08-01',
                ],
                [
                    'first_name' => 'David',
                    'last_name' => 'Kamau',
                    'email' => 'david.kamau+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 013',
                    'gender' => 'male',
                    'date_of_birth' => '1989-04-25',
                    'national_id' => '198904250007',
                    'position' => 'Sales Representative',
                    'department' => 'Sales & Marketing',
                    'employment_type' => 'full_time',
                    'status' => 'active',
                    'salary' => 900000.00,
                    'bank_account' => '0123456789007',
                    'bank_name' => 'NMB Bank',
                    'address' => 'Mwenge, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 4567',
                    'emergency_contact_name' => 'Lucy Kamau',
                    'emergency_contact_phone' => '+255 754 123 014',
                    'hire_date' => '2021-09-15',
                ],
                [
                    'first_name' => 'Anna',
                    'last_name' => 'Mkapa',
                    'email' => 'anna.mkapa+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 015',
                    'gender' => 'female',
                    'date_of_birth' => '1993-08-12',
                    'national_id' => '199308120008',
                    'position' => 'Receptionist',
                    'department' => 'Administration',
                    'employment_type' => 'full_time',
                    'status' => 'inactive',
                    'salary' => 450000.00,
                    'bank_account' => '0123456789008',
                    'bank_name' => 'Azania Bank',
                    'address' => 'Temeke, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 5678',
                    'emergency_contact_name' => 'Paul Mkapa',
                    'emergency_contact_phone' => '+255 754 123 016',
                    'hire_date' => '2020-05-10',
                ],
                [
                    'first_name' => 'James',
                    'last_name' => 'Moyo',
                    'email' => 'james.moyo+' . $client->id . '@example.com',
                    'phone' => '+255 754 123 017',
                    'gender' => 'male',
                    'date_of_birth' => '1990-10-30',
                    'national_id' => '199010300009',
                    'position' => 'IT Support Technician',
                    'department' => 'Information Technology',
                    'employment_type' => 'full_time',
                    'status' => 'active',
                    'salary' => 800000.00,
                    'bank_account' => '0123456789009',
                    'bank_name' => 'Stanbic Bank',
                    'address' => 'Kariakoo, Dar es Salaam',
                    'city' => 'Dar es Salaam',
                    'country' => 'Tanzania',
                    'postal_code' => 'P.O. Box 8901',
                    'emergency_contact_name' => 'Grace Moyo',
                    'emergency_contact_phone' => '+255 754 123 018',
                    'hire_date' => '2022-02-20',
                ],
            ];

            foreach ($employees as $index => $employeeData) {
                // Make employee_id unique per client
                $employeeData['employee_id'] = 'EMP' . str_pad($client->id, 2, '0', STR_PAD_LEFT) . str_pad($index + 1, 3, '0', STR_PAD_LEFT);
                $employeeData['client_id'] = $client->id;
                
                Employee::firstOrCreate(
                    ['employee_id' => $employeeData['employee_id'], 'client_id' => $client->id],
                    $employeeData
                );
            }
        }

        $this->command->info('Employees seeded successfully for all clients!');
    }
}
